- hosts: localhost
  
  vars:
    - oracle_host: '192.168.11.2'
    - oracle_port: '1521'
    - oracle_sid: 'noctopus11'
    - oracle_user: 'marco'
    - oracle_password: 'Temporal1'

  gather_facts: true

  environment:
    LD_LIBRARY_PATH: /opt/oracle/instantclient_12_2
   
  tasks:
  
 ########################################################################################################
    
    - name: Top 10 de Programas con mas uso de CPU
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "select rownum as rank, a.*
                from (
                    SELECT v.sid as SID ,program as Programa, v.value / (100 * 60) CPUMins
                    FROM v$statname s , v$sesstat v, v$session sess
                    WHERE s.name = 'CPU used by this session'
                    and sess.sid = v.sid
                    and v.statistic#=s.statistic#
                    and v.value>0
                ORDER BY v.value DESC) a
                where rownum < 11"
      register: reg_Query01
      delegate_to: localhost

    - set_fact: rs_Json01="{{ reg_Query01.message |from_json}}"
      when: reg_Query01.changed
      
    - debug:
        msg: "RANK: {{item.RANK}} SID: {{item.SID}} PROGRAMA: {{item.PROGRAMA}} CPUMINS: {{item.CPUMINS}} " 
      with_items: "{{ rs_Json01 }}" 

 ########################################################################################################
  
    - name: Uso de CPU
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "  select 
                    stat_name as Componente,
                    value as Valor,
                    osstat_id as Id
                  from v$osstat where cumulative ='YES'
                  order by value desc"
      register: reg_Query02
      delegate_to: localhost

    - set_fact: rs_Json02="{{ reg_Query02.message |from_json}}"
      when: reg_Query02.changed
      
    - debug:
        msg: "COMPONENTE: {{item.COMPONENTE}} VALOR: {{item.VALOR}} ID: {{item.ID}} " 
      with_items: "{{ rs_Json02 }}" 

  ########################################################################################################
  
    - name: Uso de Memoria
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT NVL(a.username,'(oracle)') AS username,
                a.module as Module,
                a.program as Program,
                Trunc(b.value/1024) AS Memory
                FROM   v$session a,
                v$sesstat b,
                v$statname c
                WHERE  a.sid = b.sid
                AND    b.statistic# = c.statistic#
                AND    c.name = 'session pga memory'
                AND    a.program IS NOT NULL
                ORDER BY b.value DESC"
      register: reg_Query03
      delegate_to: localhost

    - set_fact: rs_Json03="{{ reg_Query03.message |from_json}}"
      when: reg_Query03.changed
      
    - debug:
        msg: "USERNAME: {{item.USERNAME}} MODULE: {{item.MODULE}} PROGRAM: {{item.PROGRAM}} MEMORY: {{item.MEMORY}} " 
      with_items: "{{ rs_Json03 }}" 
 
 ############################################################################################################
 
    - name: Informacion acerca de los DataFiles
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT  file_id as FileID,
                        file_name FileName,
                        ROUND(bytes/1024/1024/1024) AS SizeGb,
                        ROUND(maxbytes/1024/1024/1024) AS MaxSizeGb,
                        autoextensible as AutoExtensible,
                        increment_by as IncrementBy,
                        status as Status
                FROM   dba_data_files
                ORDER BY file_name"
      register: reg_Query04
      delegate_to: localhost

    - set_fact: rs_Json04="{{ reg_Query04.message |from_json}}"
      when: reg_Query04.changed
      
    - debug:
        msg: "FILEID: {{item.FILEID}} FILENAME: {{item.FILENAME}} SIZEGB: {{item.SIZEGB}} MAXSIZEGB: {{item.MAXSIZEGB}} AUTOEXTENSIBLE: {{item.AUTOEXTENSIBLE}} INCREMENTBY: {{item.INCREMENTBY}} STATUS: {{item.STATUS}} " 
      with_items: "{{ rs_Json04 }}" 

################################################################################################################

    - name: Informacion acerca de Espacio Libre en Disco y DataFiles
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT a.file_name as FileName,
                  ROUND(a.bytes/1024/1024) AS SizeMb,
                  ROUND(a.maxbytes/1024/1024) AS MaxsizeMb,
                  ROUND(b.free_bytes/1024/1024) AS FreeMb,
                  ROUND((a.maxbytes-a.bytes)/1024/1024) AS GrowthMb,
                  100 - ROUND(((b.free_bytes+a.growth)/a.maxbytes) * 100) AS PctUsed
                  FROM   (SELECT file_name,
                              file_id,
                                bytes,
                              GREATEST(bytes,maxbytes) AS maxbytes,
                              GREATEST(bytes,maxbytes)-bytes AS growth
                FROM   dba_data_files) a,
              (SELeCT file_id,
                SUM(bytes) AS free_bytes
              FROM   dba_free_space
              GROUP BY file_id) b
              WHERE  a.file_id = b.file_id
              ORDER BY file_name"
      register: reg_Query05
      delegate_to: localhost

    - set_fact: rs_Json05="{{ reg_Query05.message |from_json}}"
      when: reg_Query05.changed
      
    - debug:
        msg: "FILENAME: {{item.FILENAME}} SIZEMB: {{item.SIZEMB}} MAXSIZEMB: {{item.MAXSIZEMB}} FREEMB: {{item.FREEMB}} GROWTHMB: {{item.GROWTHMB}} PCTUSED: {{item.PCTUSED}} " 
      with_items: "{{ rs_Json05 }}" 

 ########################################################################################################
    
    - name: Informacion acerca de los TableSpace
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "Select  t.tablespace_name as Tablespace,
                        t.status as Estado,  
                        ROUND(MAX(d.bytes)/1024/1024,2) as TamanoMB,
                        ROUND((MAX(d.bytes)/1024/1024) - (SUM(decode(f.bytes, NULL,0, f.bytes))/1024/1024),2) as MBUsados,   
                        ROUND(SUM(decode(f.bytes, NULL,0, f.bytes))/1024/1024,2) as MBLibres,  
                        SUBSTR(d.file_name,1,80) as FicherodeDatos  
                FROM DBA_FREE_SPACE f, DBA_DATA_FILES d,  DBA_TABLESPACES t  
                WHERE t.tablespace_name = d.tablespace_name  AND f.tablespace_name(+) = d.tablespace_name    
                AND f.file_id(+) = d.file_id GROUP BY t.tablespace_name, d.file_name, t.pct_increase, t.status 
                ORDER BY 1,3 DESC"
      register: reg_Query06
      delegate_to: localhost

    - set_fact: rs_Json06="{{ reg_Query06.message |from_json}}"
      when: reg_Query06.changed
      
    - debug:
        msg: "TABLESPACE: {{item.TABLESPACE}} ESTADO: {{item.ESTADO}} TAMANOMB: {{item.TAMANOMB}} MBUSADOS: {{item.MBUSADOS}} MBLIBRES: {{item.MBLIBRES}} FICHERODEDATOS: {{item.FICHERODEDATOS}} " 
      with_items: "{{ rs_Json06 }}" 
   
 ########################################################################################################

    - name: Informacion acerca de Redo Logs Files
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT  l.thread# as Thread,
                        lf.group# as Grupo,
                        lf.member as Member,
                        TRUNC(l.bytes/1024/1024) AS SizeMb,
                        l.status as Status,
                        l.archived as Archived,
                        lf.type as Type,
                        lf.is_recovery_dest_file AS Rdf,
                        l.sequence# as Sequence,
                        l.first_change# as FirtsChange,
                        l.next_change# as NextChange   
                FROM   v$logfile lf
                JOIN v$log l ON l.group# = lf.group#
                ORDER BY l.thread#,lf.group#, lf.member"
      register: reg_Query07
      delegate_to: localhost

    - set_fact: rs_Json07="{{ reg_Query07.message |from_json}}"
      when: reg_Query07.changed
      
    - debug:
        msg: "THREAD: {{item.THREAD}} GRUPO#: {{item.GRUPO}} MEMBER: {{item.MEMBER}} SIZEMB: {{item.SIZEMB}} STATUS: {{item.STATUS}} ARCHIVED: {{item.ARCHIVED}} TYPE: {{item.TYPE}} RDF: {{item.RDF}} SEQUENCE: {{item.SEQUENCE}} FIRTSCHANGE: {{item.FIRTSCHANGE}} NEXTCHANGE: {{item.NEXTCHANGE}} " 
      with_items: "{{ rs_Json07 }}" 
      
 ########################################################################################################

    - name: Informacion acerca de I/O por Datafile
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT Substr(d.name,1,50) as FileName,
                       f.phyblkrd as BlocksRead,
                       f.phyblkwrt as BlocksWritten,
                       f.phyblkrd + f.phyblkwrt Total_IO
                FROM   v$filestat f,
                       v$datafile d
                WHERE  d.file# = f.file#
                ORDER BY f.phyblkrd + f.phyblkwrt DESC"
      register: reg_Query08
      delegate_to: localhost

    - set_fact: rs_Json08="{{ reg_Query08.message |from_json}}"
      when: reg_Query08.changed
      
    - debug:
        msg: "FILENAME: {{item.FILENAME}} BLOCKSREAD: {{item.BLOCKSREAD}} BLOCKSWRITTEN: {{item.BLOCKSWRITTEN}} TOTAL_IO: {{item.TOTAL_IO}} " 
      with_items: "{{ rs_Json08 }}" 
      
########################################################################################################

    - name: Informacion de la Cantidad de I/O por cada TempFile
      orclqry:
        host: '{{ oracle_host }}'
        port: '{{ oracle_port }}'
        sid: '{{ oracle_sid }}'
        user: '{{ oracle_user }}'
        password: '{{ oracle_password }}'
        query: "SELECT SUBSTR(t.name,1,50) AS FileName,
                        f.phyblkrd AS BlocksRead,
                        f.phyblkwrt AS BlocksWritten,
                        f.phyblkrd + f.phyblkwrt AS Total_IO
                FROM   v$tempstat f,
                       v$tempfile t
                WHERE  t.file# = f.file#
                ORDER BY f.phyblkrd + f.phyblkwrt DESC"
      register: reg_Query09
      delegate_to: localhost

    - set_fact: rs_Json09="{{ reg_Query09.message |from_json}}"
      when: reg_Query09.changed
      
    - debug:
        msg: "FILENAME: {{item.FILENAME}} BLOCKSREAD: {{item.BLOCKSREAD}} BLOCKSWRITTEN: {{item.BLOCKSWRITTEN}} TOTAL_IO: {{item.TOTAL_IO}} " 
      with_items: "{{ rs_Json09 }}" 
   
########################################################################################################